### PR TITLE
add cli test (and others)

### PR DESCRIPTION
**Pull request by PaulineMauryL**

### CODE REVIEW

**Comment by PaulineMauryL** [comment]
## Coverage report


 <details><summary>Click to see where and how coverage changed</summary><table><thead>
  <tr><th>File</th><th>Statements</th><th>Missing</th><th>Coverage</th><th>Coverage<br>(new stmts)</th><th>Lines missing</th></tr>
</thead>
<tbody><tr>
<td colspan="6">&nbsp;&nbsp;<b>server/lomas_server</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-6f14a4ab67fef3f3365196fae801d5411a894f4ad3b6a93b1025f75e5aa22c76">mongodb_admin.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-6f14a4ab67fef3f3365196fae801d5411a894f4ad3b6a93b1025f75e5aa22c76"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-6f14a4ab67fef3f3365196fae801d5411a894f4ad3b6a93b1025f75e5aa22c76"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-6f14a4ab67fef3f3365196fae801d5411a894f4ad3b6a93b1025f75e5aa22c76"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-6f14a4ab67fef3f3365196fae801d5411a894f4ad3b6a93b1025f75e5aa22c76"></a></td><td></td><tr>
<td colspan="6">&nbsp;&nbsp;<b>server/lomas_server/tests</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc">test_mongodb_admin.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bcR55-R62">55-62</a></td></tbody>
<tfoot>
<tr>
<td><b>Project Total</b></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/80/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td>&nbsp;</td>
</tr>
</tfoot>
</table>

<sub>

This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)

</sub>
</details>

**Comment by PaulineMauryL** [comment]
found a few bug in the cli ^^ should be good now

**Comment by PaulineMauryL** [comment]
almost all remaining non tested code is related to S3

**Comment by PaulineMauryL** [comment]
unfortunatelly, I merged #79 in the wrong branch so it is partly a duplicate.

**Review by LancelotMarti — APPROVED** [review]

**Pull request merged**
