### PR TITLE
Feature DiffPrivLib: PR for DiffPrivLib go to this branch until ready to go

### PR DESCRIPTION
**Pull request by PaulineMauryL**

### CODE REVIEW

**Comment by 0f4d0335** [comment]
Oh, I was just going to report issues with non-http exceptions that crash the server. I will check back next week. Thanks.

**Comment by PaulineMauryL** [comment]
## Coverage report


 <details><summary>Click to see where and how coverage changed</summary><table><thead>
  <tr><th>File</th><th>Statements</th><th>Missing</th><th>Coverage</th><th>Coverage<br>(new stmts)</th><th>Lines missing</th></tr>
</thead>
<tbody><tr>
<td colspan="6">&nbsp;&nbsp;<b>server/lomas_server</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-58a9fc5a17540b2fe4c3e40437bafa37681f53d6daf18f5d14cef65f52b483ad">app.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-58a9fc5a17540b2fe4c3e40437bafa37681f53d6daf18f5d14cef65f52b483ad"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-58a9fc5a17540b2fe4c3e40437bafa37681f53d6daf18f5d14cef65f52b483ad"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-58a9fc5a17540b2fe4c3e40437bafa37681f53d6daf18f5d14cef65f52b483ad"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-58a9fc5a17540b2fe4c3e40437bafa37681f53d6daf18f5d14cef65f52b483ad"></a></td><td></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4ef5cc30e18c28ff2745a2889f8b0ff899cca1f8bbf06fc33d0333dde1f48465">constants.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4ef5cc30e18c28ff2745a2889f8b0ff899cca1f8bbf06fc33d0333dde1f48465"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4ef5cc30e18c28ff2745a2889f8b0ff899cca1f8bbf06fc33d0333dde1f48465"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4ef5cc30e18c28ff2745a2889f8b0ff899cca1f8bbf06fc33d0333dde1f48465"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4ef5cc30e18c28ff2745a2889f8b0ff899cca1f8bbf06fc33d0333dde1f48465"></a></td><td></td><tr>
<td colspan="6">&nbsp;&nbsp;<b>server/lomas_server/admin_database</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-e3c72c43ab1bc6e43189114b2e15c55f34c24d8b0e2a0e66a0eb3f71d1db4f4e">admin_database.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-e3c72c43ab1bc6e43189114b2e15c55f34c24d8b0e2a0e66a0eb3f71d1db4f4e"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-e3c72c43ab1bc6e43189114b2e15c55f34c24d8b0e2a0e66a0eb3f71d1db4f4e"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-e3c72c43ab1bc6e43189114b2e15c55f34c24d8b0e2a0e66a0eb3f71d1db4f4e"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-e3c72c43ab1bc6e43189114b2e15c55f34c24d8b0e2a0e66a0eb3f71d1db4f4e"></a></td><td></td><tr>
<td colspan="6">&nbsp;&nbsp;<b>server/lomas_server/dp_queries/dp_libraries</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-b473422d8b3c6f3eadb3ae6ff414f4d7e119f696c18454d41a0358e4aa6778d3">diffprivlib.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-b473422d8b3c6f3eadb3ae6ff414f4d7e119f696c18454d41a0358e4aa6778d3"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-b473422d8b3c6f3eadb3ae6ff414f4d7e119f696c18454d41a0358e4aa6778d3"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-b473422d8b3c6f3eadb3ae6ff414f4d7e119f696c18454d41a0358e4aa6778d3"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-b473422d8b3c6f3eadb3ae6ff414f4d7e119f696c18454d41a0358e4aa6778d3"></a></td><td></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652">diffprivlib_utils.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652"></a></td><td><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652R31-R49">31-49</a>, <a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652R58-R59">58-59</a>, <a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-c182145cf012a11d1f2055d00306cba35757a8216acbbf665892d58e6544b652R90-R95">90-95</a></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-bf8e93ac1c3b582ad4082be55cec7b0ef4eae5379fa751ea9a5bf6ecc8cfbc76">utils.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-bf8e93ac1c3b582ad4082be55cec7b0ef4eae5379fa751ea9a5bf6ecc8cfbc76"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-bf8e93ac1c3b582ad4082be55cec7b0ef4eae5379fa751ea9a5bf6ecc8cfbc76"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-bf8e93ac1c3b582ad4082be55cec7b0ef4eae5379fa751ea9a5bf6ecc8cfbc76"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-bf8e93ac1c3b582ad4082be55cec7b0ef4eae5379fa751ea9a5bf6ecc8cfbc76"></a></td><td></td><tr>
<td colspan="6">&nbsp;&nbsp;<b>server/lomas_server/tests</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-7f7d18385b324497d5ebcf51c3e0c0172158683cd7f916a75a261815c51f617c">test_api.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-7f7d18385b324497d5ebcf51c3e0c0172158683cd7f916a75a261815c51f617c"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-7f7d18385b324497d5ebcf51c3e0c0172158683cd7f916a75a261815c51f617c"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-7f7d18385b324497d5ebcf51c3e0c0172158683cd7f916a75a261815c51f617c"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-7f7d18385b324497d5ebcf51c3e0c0172158683cd7f916a75a261815c51f617c"></a></td><td></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-0ce03d082552382cfaeadeba39a2db7a04f14d000a7ee3ef20e205a0dc05a0f2">test_api_diffprivlib.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-0ce03d082552382cfaeadeba39a2db7a04f14d000a7ee3ef20e205a0dc05a0f2"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-0ce03d082552382cfaeadeba39a2db7a04f14d000a7ee3ef20e205a0dc05a0f2"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-0ce03d082552382cfaeadeba39a2db7a04f14d000a7ee3ef20e205a0dc05a0f2"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-0ce03d082552382cfaeadeba39a2db7a04f14d000a7ee3ef20e205a0dc05a0f2"></a></td><td></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc">test_mongodb_admin.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8860acb398146823e4b75c9bac2b9fc191e2f220076e2a3c57b9e20ffc2634bc"></a></td><td></td><tr>
<td colspan="6">&nbsp;&nbsp;<b>server/lomas_server/utils</b></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8f8207a072080f6d0b7cf718ebf9d60f67c21d1d7218facf059a08304a8a8aa9">example_inputs.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8f8207a072080f6d0b7cf718ebf9d60f67c21d1d7218facf059a08304a8a8aa9"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8f8207a072080f6d0b7cf718ebf9d60f67c21d1d7218facf059a08304a8a8aa9"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8f8207a072080f6d0b7cf718ebf9d60f67c21d1d7218facf059a08304a8a8aa9"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-8f8207a072080f6d0b7cf718ebf9d60f67c21d1d7218facf059a08304a8a8aa9"></a></td><td></td><tr>
<td>&nbsp;&nbsp;<a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-9e227ec45a88e24b7a4cfa12e0abe34434bf57f3533aa3d5782d82c4c0beacd8">input_models.py</a></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-9e227ec45a88e24b7a4cfa12e0abe34434bf57f3533aa3d5782d82c4c0beacd8"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-9e227ec45a88e24b7a4cfa12e0abe34434bf57f3533aa3d5782d82c4c0beacd8"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-9e227ec45a88e24b7a4cfa12e0abe34434bf57f3533aa3d5782d82c4c0beacd8"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-9e227ec45a88e24b7a4cfa12e0abe34434bf57f3533aa3d5782d82c4c0beacd8"></a></td><td></td></tbody>
<tfoot>
<tr>
<td><b>Project Total</b></td>
<td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td align="center"><a href="https://github.com/dscc-admin-ch/lomas/pull/116/files#diff-4b0bf2efa3367c0072ac2bf1e234e703dc46b47aaa4fe9d3b01737b1a15752b1"></a></td><td>&nbsp;</td>
</tr>
</tfoot>
</table>

<sub>

This report was generated by [python-coverage-comment-action](https://github.com/py-cov-action/python-coverage-comment-action)

</sub>
</details>

**Comment by PaulineMauryL** [comment]
See here for diffprivlib-logger: https://github.com/dscc-admin-ch/diffprivlib-logger

**Comment by PaulineMauryL** [comment]
I think the PR is ready to go. If it is alright with you @lamd91 we can do further work on the scores later!

**Review by lamd91 — APPROVED** [review]

**Pull request merged**
